name: Build, Push to ACR,

on:
  push:
    branches: 
      - azure-testing

# Allow Github to expose OIDC token to the job
permissions:
  id-token: write
  contents: read

env:
  # Azure Container Registry settings
  ACR_NAME: sammystestregistry                 # e.g. myregistry (without .azurecr.io)
  ACR_LOGIN_SERVER: sammystestregistry.azurecr.io   # e.g. myregistry.azurecr.io
  IMAGE_NAME: sammys-test-image

jobs:
  build-and-push:
    name: Build & Push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} #a unique GUID identifying a registered application in Microsoft Entra ID (formerly Azure Active Directory), used for authentication in the Azure SDK and environment variables
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} #a unique GUID (Globally Unique Identifier) representing your organization's dedicated instance of Microsoft Entra ID (formerly Azure Active Directory)
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} #a unique, alphanumeric GUID (Globally Unique Identifier) that identifies a specific Azure subscription, acting as a container for billing and resource management

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .
          docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

      - name: Push Image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest